services:
  mc:
    image: itzg/minecraft-server:java17-openj9
    container_name: minecraft-java
    restart: unless-stopped
    ports:
      - "25565:25565"
      - "24454:24454/udp"
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      TYPE: FABRIC
      VERSION: "1.19.3"
      PACKWIZ_URL: https://games.somacode.app/minecraft-mods/pack.toml
    tty: true
    stdin_open: true
    volumes:
      - ./minecraft-data:/data:Z